### ISSUE TITLE
android issue FATAL EXCEPTION:  

### ISSUE THREAD

**Issue by liquidzym** [runemadsen/HTTP-Requests-for-Processing#21]
i'm testing with really simple android app which save the captured image then upload to the server
on each time during the http post session the app got crashed,reported as following:

FATAL EXCEPTION: Animation Thread
java.lang.NoSuchMethodError: org.apache.http.util.EntityUtils.consume
	at http.requests.PostRequest.send(Unknown Source)
	at processing.test.android_image.android_image.postImg(android_image.java:145)
	at processing.test.android_image.android_image.draw(android_image.java:56)
	at processing.core.PApplet.handleDraw(Unknown Source)
	at processing.core.PGraphicsAndroid2D.requestDraw(Unknown Source)
	at processing.core.PApplet.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:841)

but without any issue running on desktop. any ideas?

**Comment by ptmcg** [comment]
I believe I am having this same error. Runs ok from desktop but fails when run from my Android phone. This program illustrates the problem:

```
import http.requests.*;

public void setup() 
{
  size(800,800);
  background(32);
  smooth();
}

public void draw() {
}

public void mouseReleased() {
  JSONObject rpt = new JSONObject();
  rpt.setLong("ts", System.currentTimeMillis());
  JSONArray latlng = new JSONArray();
  latlng.append(mouseX);
  latlng.append(mouseY);
  rpt.setJSONArray("posn", latlng); 
  PostRequest post = new PostRequest("http://54.209.226.233:31416/locn_report", "UTF-8");
  post.addHeader("Content-Type", "application/json");
  post.addHeader("Connection", "close");
  post.addData("", rpt.format(0));
  post.send();
}
```

**Comment by mahler52** [comment]
I too. I wrote a small sketch . It calls a website using getRequest. Simple. It works well in java mode but fails when downloaded to my 2 android tablet/phones . Same fatal exception of yours. I was considering to use another library but I don t know any other http library.

**Comment by gtricho** [comment]
I had the same issue but I think I solved it by deleting all empty lines from the code. It's strange but it worked for me!
